-- ==========[ ATTENTION: FULL DATABASE RESET SCRIPT ]==========
-- This script will completely WIPE and REBUILD your public schema.
-- Execute this in your Supabase SQL Editor to ensure a clean slate.
-- =================================================================

-- Step 1: Drop all existing tables in the correct order to avoid foreign key conflicts (if any).
DROP TABLE IF EXISTS public.customers CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.site_settings CASCADE;

-- Step 2: Recreate the tables with simple, correct schemas.

-- Table for Products
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    status TEXT NOT NULL,
    total_sales BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    image_url TEXT
);

-- Table for general Site Settings
CREATE TABLE public.site_settings (
    id INT PRIMARY KEY,
    logo_url TEXT,
    gallery_images TEXT[]
);

-- Table for Customers
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    total_spent NUMERIC DEFAULT 0,
    city TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- Step 3: IMPORTANT - Disable Row Level Security (RLS) for all tables.
-- This allows the API to access the data using the service_role key.
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;


-- Step 4: Insert the single mandatory row for site settings.
-- This prevents the API from failing if the settings row does not exist.
INSERT INTO public.site_settings (id, logo_url, gallery_images)
VALUES (1, '', '{}')
ON CONFLICT (id) DO NOTHING;


-- Step 5: Final confirmation message.
SELECT 'SUCCESS: Database has been completely reset. Tables (products, site_settings, customers) are created and RLS is OFF.';

    